name: Validate filenames & JSON informations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Collecting file paths
        run: |
          echo "FILE_PATHS=$(find ./tokens -type f -name '*info.json' -printf '%p,'| sed 's/,$//' )" >> $GITHUB_ENV
        shell: bash
      - id: files
        name: Validate filenames
        uses: jitterbit/get-changed-files@v1
        # with:
        #   format: 'json'
      - run: |
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"
          for file in ${{ steps.files.outputs.added }}; do
            echo "$file added"
            if [[ ${file} != *"/info.json"* && ${file} != *"/logo.png"* && ${file} != *"/logo.svg"* ]]; then
              echo "Filename ${file} isn't expected!"
              exit 1
            fi

            DIR=`basename $(dirname $file)`
          done
        shell: bash
      - name: Validate file size
        run: |
          source .github/snippet.sh; validate_file_size
        shell: bash
      - name: Validate token existence
        run: |
          source .github/snippet.sh; validate_token_existence
        shell: bash
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ${{ env.FILE_PATHS }}
        