name: Validate JSON

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Collecting file paths
        run: |
          echo "FILE_PATHS=$(find ./tokens -type f -name '*info.json' -printf '%p,'| sed 's/,$//' )" >> $GITHUB_ENV
        shell: bash
      - id: files
        name: Validate json filenames
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"
          for added_file in ${added_files[@]}; do
            if [[ ${added_file} != *"/info.json"* ] | [[ ${added_file} != *"/logo.png"* ]] | [[ ${added_file} != *"/logo.svg"* ]] ]; then
              echo "Filename ${added_file} isn't expected!"
              exit 1
            fi
          done
        shell: bash
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.json
          INPUT_JSONS: ${{ env.FILE_PATHS }}
        